<?php

return [
	'TWILIO_SID' => '',
	'TWILIO_TOKEN' => '',
	'TWILIO_FROM' => '',
	'LOGOUT_URL' => env('SITE_URL'),

	'user_account_number' => '',
	'user_account_name' => 'spaculus Account',
	'user_account_api_key' => '',

	'account_user_name' => '',
	'account_password' => '',
	
	'site_logo_folder' => 'public/uploads/logo',
	'site_favicon_folder' => 'public/uploads/favicon',
	'client_picture_folder' => 'public/uploads/client_pictures',
	'notifications_img' => 'public/uploads/notifications_img',
	'admin_picture_folder' => 'uploads/admin_pictures',
	'refferal_partner_folder' => 'public/uploads/refferal_partners',
	'banner_folder' => 'public/uploads/banners',
	'blog_post_folder' => 'public/uploads/blog_posts',
    'default_picture' => 'admin/files/user-image.png',
	'forum_attachments_folder' => 'public/uploads/forum_attachments',
	'support_ticket_files' => 'public/uploads/support_ticket_files',

    'open_ticket_status'	=> 1,
    
	'in_progress_ticket_status'	=> 2,

	'default_ticket_status'	=>	1,

	'closed_ticket_status'	=> 3,

	'reopen_ticket_status'	=> 4,
    
    'route_prefix' => [		
		'admin' => '/administrator',		
		'client' => '/user',	
		'refferal' => '/refferal-partner'	
    ],
    'nium_transaction_status' => [
		'IN_PROCESS' => 'PROCESSING',
		'AWAITING_FUNDS' => 'AWAITING FUNDS',
		'INFO_REQUESTED' => 'INFO REQUESTED',
		'COMPLIANCE_REJECTED' => 'COMPLIANCE REJECTED',
		'SENT_TO_BANK' => 'SENT TO BANK',
		'PG_PROCESSING' => 'IN PROCESS',
		'PAID' => 'PAID',
		'RETURNED' => 'RETURNED',
		'REJECTED' => 'REJECTED',
		'CANCELLED' => 'CANCELLED',
		'FAILED' => 'FAILED',
		'INITIATE' => 'INITIATE',
		'PAYMENT_RETURN' => 'PAYMENT RETURN',
	],
    'email_template' => [
		'email_verification' => 1,
		'admin_welcome_email' => 2,
		'password_reset_email' => 3,
		'password_change_notification' => 4,
		'update_email_verification' => 5,
		'support_ticket_reply_submission' => 6,
		'support_ticket_submission' => 7,
		'email_update_notification' => 8,
		'email_notification_reminders_subscription' => 10,
		'email_notificationUpdate_account_user' => 21,
		'client_welcome_email' => 9,
		'user_forgot_password_otp' => 11,
		'user_payment_verification_otp' => 12,
		'user_email_verification_otp' => 13,
		'payment_detail_email_to_admin' => 14,
		'payment_detail_email_to_Beneficiary' => 15,
		'NPP_return_email_to_admin' => 16,
		'direct_entry_dishonour_email_to_admin' => 17,
		'payment_detail_email_to_user' => 18,
		'payment_status_update_email_to_user' => 19,
		'client_swiftwelcome_email' => 20, 
	],
	'email_types' => [
		'email_verification' => 1,
		'reset_password' => 2,
		'reset_password_notification' => 3,
		'change_password_notification' => 4,
		'support_ticket_submission' => 5,
		'support_ticket_reply_submission' => 6,
		'subscription_notification' => 7,
		'welcome_email' => 8,
		'referral_welcome_email' => 9,
		'email_update_notification' => 10,
		'profile_update_notification' => 11,
		'employee_welcome_email' => 12,
		'client_data_update_email' => 13,
		'client_welcome_email' => 14,
	],
	'contactEmailSubject' => 'Contact form submission',
	'applicationCallbackEmailSubject' => 'Application Callback form submission',
	'bcc_email_address' => 'abcd@yopmail.com',
	'states' => ['NSW','QLD','SA','TAS','VIC','WA'],
	'permissions' => [
		'create' => 1,
		'edit' => 2,
		'delete' => 3,
		'view' => 4,
		//'approve' => 5,
		'verify' => 6,
		'assign' =>  7,
		'internal_verify' => 8,
		'status'=>5
	],
	'admin_modules' => [
		'admin_users' => 1,
		'clients' => 2,
		'roles_permissions' => 3,
		'contact' => 4,
		'support_ticket_category' => 5,
		'settings' => 6,
		'email_templates' => 7,
		'refferal_partners' => 8,
		//'currency_settings' => 9,
		'add_money_in_nium_account' => 10,
		// 'transactions_send_money' => 11,
		'transactions_recieved_money' => 11,
		'library' => 12,
		'activity_log' => 13,
		'events' => 14,
		'beneficiars' => 18,
		'faq' => 15,
		'npp_returns' => 16,
		'purpose_codes' => 17,
		'cms_settings' => 9,
		'subscription' => 18,
		'voice_type' => 19,
		'transaction' => 20,
		'dashboard' => 21,
	],
	'transaction_status_color' => [
		'IN_PROCESS' => 'yellow',
		'INITIATE' => 'orange',
		'PAID' => 'green',
		'CANCELLED' => 'red',
	],
	'main_currencies' => [
		1 => 'AUD',
		2 => 'CAD',
		3 => 'EUR',
		4 => 'GBP',
		5 => 'HKB',
		6 => 'INR',
	],
	'from_currency'  => [
		'AUD'  => 'AUD',
		// 'CAD'  => 'CAD',
		// 'EUR'  => 'EUR',
		// 'GBP'  => 'GBP',
		// 'HKB'  => 'HKB',
		// 'INR'  => 'INR',
	],
	'to_currency' => [
		// 'AUD'  => 'AUD',
		// 'CAD'  => 'CAD',
		// 'EUR'  => 'EUR',
		// 'GBP'  => 'GBP',
		// 'HKB'  => 'HKB',
		// 'SGD'  => 'SGD',
		// 'PHP'  => 'PHP',
		'INR'  => 'INR',
		'BDT'  => 'BDT',
		'NPR'  => 'NPR',
		'LKR'  => 'LKR',
		'USD'  => 'USD',
	],
	// country images
	'country_flag' => [
		// 'AUD'  => 'AUD',
		// 'CAD'  => 'CAD',
		// 'EUR'  => 'EUR',
		// 'GBP'  => 'GBP',
		// 'HKB'  => 'HKB',
		// 'INR'  => 'INR',
		// 'SGD'  => 'SGD',
		// 'PHP'  => 'PHP',
		'INR'  => 'INR',
		'BDT'  => 'BDT',
		'NPR'  => 'NPR',
		'LKR'  => 'LKR',
		'USD'  => 'USD',
	],
	
	'user_types' => [
		'admin' => 'A',
		'client' => 'C',
		'referral' => 'R',
		'employee' => 'E'
	],
	'user_types_reverse' => [
		'A' => 'Admin',
		'C' => 'Client',
		'R' => 'Referral partner',
		'E' => 'Employee'
	]
];

?>